# Generated by Django 5.0.1 on 2024-01-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('text', models.TextField()),
                ('new_time', models.DateTimeField(auto_now_add=True)),
                ('new_png', models.ImageField(upload_to='png/%Y/%n/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('task_time', models.DateTimeField(auto_now_add=True)),
                ('test', models.TextField()),
            ],
        ),
    ]
