# Generated by Django 5.0 on 2024-04-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
