# Generated by Django 5.0 on 2024-04-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('task_time', models.DateTimeField(auto_now_add=True)),
                ('test', models.TextField()),
                ('complexity', models.TextField()),
            ],
        ),
    ]
