# Generated by Django 5.0 on 2024-04-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_task_complexity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
