# Generated by Django 5.0 on 2024-04-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_forum_subjectforum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
