# Generated by Django 5.0 on 2024-04-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_forum_delete_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('text', models.TextField()),
                ('new_time', models.DateTimeField(auto_now_add=True)),
                ('new_png', models.ImageField(upload_to='png/%Y/%n/')),
                ('user', models.TextField()),
            ],
        ),
    ]
