# Generated by Django 5.0 on 2024-04-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_rename_new_png_new_png'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='png',
            field=models.ImageField(upload_to='img'),
        ),
    ]
